StudentCalendar/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('cal/', include('calapp.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
]

calapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('caltest/', views.indextest, name='indextest'),
    path('newtask/', views.new_task, name='newtask'),
    path('deletetask/', views.delete_task, name='deletetask'),
    path('deleteevent/', views.delete_event, name='deleteevent'),
]

calapp/models.py
from django.db import models
from django.conf import settings

# Create your models here.
# class User(models.Model):
    # username = models.CharField(max_length=200)
    # pass_hash = models.CharField(max_length=128)
    # pass_salt = models.CharField(max_length=128)
    # email = models.EmailField()
    
class Category(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    category_name = models.CharField(max_length=300)
    parent_category = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True)
    color_hex = models.CharField(max_length=6)
   
class Task(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    task_name = models.CharField(max_length=300)
    deadline = models.DateTimeField()
    PRIORITY_CHOICES = (
        ("HIGH_PRI", "High"),
        ("MED_PRI", "Medium"),
        ("LOW_PRI", "Low"),
    )
    priority = models.CharField(max_length=15, choices=PRIORITY_CHOICES, default="MED_PRI")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    completed = models.BooleanField()
    estimatedDuration = models.DurationField(null=True, blank=True)
    
class Subtask(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    subtask_name = models.CharField(max_length=300)
    parent_task = models.ForeignKey(Task, on_delete=models.CASCADE)
    completed = models.BooleanField()
    
class Event(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    event_name = models.CharField(max_length=300)
    parent_task = models.ForeignKey(Task, on_delete=models.CASCADE, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    start_time = models.DateTimeField()
    duration = models.DurationField()

calapp/forms.py
from django import forms

from django.forms import ModelForm

from .models import Event
from .models import Task
from .models import Subtask
from .models import Category


class TaskForm(forms.Form):

    user = None
        
    task_name = forms.CharField(label="Task Name", max_length=300)
    task_deadline = forms.DateTimeField(label="Deadline")
    task_priority = forms.ChoiceField(label="Priority", choices=Task.PRIORITY_CHOICES)
    task_category = None
    #task_category = forms.ModelChoiceField(queryset=Category.objects.filter(user__exact=request.user).all, empty_label="(No Category)")
    task_duration = forms.DurationField(label="Estimated Duration")
    
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(TaskForm, self).__init__(*args, **kwargs)
        self.task_category = forms.ModelChoiceField(queryset=Category.objects.filter(user__exact=self.user).all(), empty_label="(No Category)")
        
        
class ModelTaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ["task_name", "deadline", "priority", "category", "estimatedDuration"]

calapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.template import loader

from .models import Event
from .models import Task
from .models import Subtask
from .models import Category



# Create your views here.
def index(request):
    if (not request.user.is_authenticated):
        return HttpResponse("Not logged in!")
        
    all_events = Event.objects.filter(user__exact=request.user).order_by("event_name")
    tasks = Task.objects.filter(user__exact=request.user).order_by("deadline")
    subtasks = Subtask.objects.filter(user__exact=request.user).all
    categories = Category.objects.filter(user__exact=request.user).all
    
    template = loader.get_template("calapp/index.html")
    context = {
        "all_events": all_events,
        "tasks": tasks,
        "subtasks": subtasks,
        "categories": categories,
    }
    return HttpResponse(template.render(context, request))
    
# Create your views here.
def indextest(request):
    if (not request.user.is_authenticated):
        return HttpResponse("Not logged in!")
        
    all_events = Event.objects.filter(user__exact=request.user).order_by("event_name")
    tasks = Task.objects.filter(user__exact=request.user).order_by("deadline")
    subtasks = Subtask.objects.filter(user__exact=request.user).all
    categories = Category.objects.filter(user__exact=request.user).all
    
    mon_events = Event.objects.filter(user__exact=request.user).filter(start_time__week_day=2).order_by("event_name")
    tue_events = Event.objects.filter(user__exact=request.user).filter(start_time__week_day=3).order_by("event_name")
    wed_events = Event.objects.filter(user__exact=request.user).filter(start_time__week_day=4).order_by("event_name")
    thr_events = Event.objects.filter(user__exact=request.user).filter(start_time__week_day=5).order_by("event_name")
    fri_events = Event.objects.filter(user__exact=request.user).filter(start_time__week_day=6).order_by("event_name")
    
    for event in all_events:
        event.ending_time = event.start_time + event.duration
        
    for event in mon_events:
        event.ending_time = event.start_time + event.duration
        
    for event in tue_events:
        event.ending_time = event.start_time + event.duration
        
    for event in wed_events:
        event.ending_time = event.start_time + event.duration
        
    for event in thr_events:
        event.ending_time = event.start_time + event.duration
        
    for event in fri_events:
        event.ending_time = event.start_time + event.duration
    
    template = loader.get_template("calapp/caltest.html")
    context = {
        "all_events": all_events,
        "tasks": tasks,
        "subtasks": subtasks,
        "categories": categories,
        "mon_events": mon_events,
        "tue_events": tue_events,
        "wed_events": wed_events,
        "thr_events": thr_events,
        "fri_events": fri_events,
    }
    return HttpResponse(template.render(context, request))
    
    

from .forms import TaskForm
from .forms import ModelTaskForm
def new_task(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ModelTaskForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            newTask = Task(
                user=request.user,
                task_name=form.cleaned_data['task_name'],
                deadline=form.cleaned_data['deadline'],
                priority=form.cleaned_data['priority'],
                category=form.cleaned_data['category'],
                completed=False,
                estimatedDuration=form.cleaned_data['estimatedDuration'],
            )
            newTask.save()
            # redirect to a new URL:
            return HttpResponseRedirect('/cal/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ModelTaskForm()

    return render(request, 'calapp/newtask.html', {'form': form})
    

def delete_task(request):
    task_id_to_delete = request.GET.get("id", default="BADID")
    if task_id_to_delete != "BADID":
        Task.objects.filter(id__exact=task_id_to_delete).delete()
    return HttpResponseRedirect('/cal/')
    
def delete_event(request):
    event_id_to_delete = request.GET.get("id", default="BADID")
    if event_id_to_delete != "BADID":
        Event.objects.filter(id__exact=event_id_to_delete).delete()
    return HttpResponseRedirect('/cal/')
    
from . import allocateTime
def allocate_time_for_task(request):
    task_id_to_alloc = request.GET.get("id", default="BADID")
    if task_id_to_alloc == "BADID":
        return HttpResponseRedirect('/cal/')
    got_task = Task.objects.get(id__exact=task_id_to_alloc)

calapp/templates/calapp/caltest.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script>document.getElementsByTagName("html")[0].className += " js";</script>
  <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
  <title>Calendar Task System</title>
</head>
<body>


<!-- License: https://codyhouse.co/mit -->



  <header class="cd-main-header text-center flex flex-column flex-center">
    <p class="margin-top-md margin-bottom-xl"></p>

    <h1 class="text-xl">G.N.C.alendar Task Management Utility</h1>
  </header>

  <div class="cd-schedule cd-schedule--loading margin-top-lg margin-bottom-lg js-cd-schedule">
    <div class="cd-schedule__timeline">
      <ul>
        <li><span>09:00</span></li>
        <li><span>09:30</span></li>
        <li><span>10:00</span></li>
        <li><span>10:30</span></li>
        <li><span>11:00</span></li>
        <li><span>11:30</span></li>
        <li><span>12:00</span></li>
        <li><span>12:30</span></li>
        <li><span>13:00</span></li>
        <li><span>13:30</span></li>
        <li><span>14:00</span></li>
        <li><span>14:30</span></li>
        <li><span>15:00</span></li>
        <li><span>15:30</span></li>
        <li><span>16:00</span></li>
        <li><span>16:30</span></li>
        <li><span>17:00</span></li>
        <li><span>17:30</span></li>
        <li><span>18:00</span></li>
      </ul>
    </div> <!-- .cd-schedule__timeline -->
  
    <div class="cd-schedule__events">
      <ul>
        <li class="cd-schedule__group">
          <div class="cd-schedule__top-info"><span>Monday</span></div>
  
          <ul>
            {% for event in mon_events %}
                <li class="cd-schedule__event">
                  <a data-start="{{ event.start_time | date:'H:i' }}" data-end="{{ event.end_time | date:'H:i' }}" data-content="event-abs-circuit" data-event="event-1" href="#0">
                    <em class="cd-schedule__name">{{ event.event_name }}</em>
                  </a>
                </li>
            {% endfor %}
          </ul>
        </li>
  
        <li class="cd-schedule__group">
          <div class="cd-schedule__top-info"><span>Tuesday</span></div>
  
          <ul>
            {% for event in tue_events %}
                <li class="cd-schedule__event">
                  <a data-start="{{ event.start_time | date:'H:i' }}" data-end="{{ event.end_time | date:'H:i' }}" data-content="event-abs-circuit" data-event="event-1" href="#0">
                    <em class="cd-schedule__name">{{ event.event_name }}</em>
                  </a>
                </li>
            {% endfor %}
          </ul>
        </li>
  
        <li class="cd-schedule__group">
          <div class="cd-schedule__top-info"><span>Wednesday</span></div>
  
          <ul>
            {% for event in wed_events %}
                <li class="cd-schedule__event">
                  <a data-start="{{ event.start_time | date:'H:i' }}" data-end="{{ event.end_time | date:'H:i' }}" data-content="event-abs-circuit" data-event="event-1" href="#0">
                    <em class="cd-schedule__name">{{ event.event_name }}</em>
                  </a>
                </li>
            {% endfor %}
          </ul>
        </li>
  
        <li class="cd-schedule__group">
          <div class="cd-schedule__top-info"><span>Thursday</span></div>
  
          <ul>
            {% for event in thr_events %}
                <li class="cd-schedule__event">
                  <a data-start="{{ event.start_time | date:'H:i' }}" data-end="{{ event.end_time | date:'H:i' }}" data-content="event-abs-circuit" data-event="event-1" href="#0">
                    <em class="cd-schedule__name">{{ event.event_name }}</em>
                  </a>
                </li>
            {% endfor %}
          </ul>
        </li>
  
        <li class="cd-schedule__group">
          <div class="cd-schedule__top-info"><span>Friday</span></div>
  
          <ul>
            {% for event in fri_events %}
                <li class="cd-schedule__event">
                  <a data-start="{{ event.start_time | date:'H:i' }}" data-end="{{ event.end_time | date:'H:i' }}" data-content="event-abs-circuit" data-event="event-1" href="#0">
                    <em class="cd-schedule__name">{{ event.event_name }}</em>
                  </a>
                </li>
            {% endfor %}
          </ul>
        </li>
      </ul>
    </div>
  
    <div class="cd-schedule-modal">
      <header class="cd-schedule-modal__header">
        <div class="cd-schedule-modal__content">
          <span class="cd-schedule-modal__date"></span>
          <h3 class="cd-schedule-modal__name"></h3>
        </div>
  
        <div class="cd-schedule-modal__header-bg"></div>
      </header>
  
      <div class="cd-schedule-modal__body">
        <div class="cd-schedule-modal__event-info"></div>
        <div class="cd-schedule-modal__body-bg"></div>
      </div>
  
      <a href="#0" class="cd-schedule-modal__close text-replace">Close</a>
    </div>
  
    <div class="cd-schedule__cover-layer"></div>
  </div> <!-- .cd-schedule -->

  <script src="{% static "assets/js/util.js" %}"></script> <!-- util functions included in the CodyHouse framework -->
  <script src="{% static "assets/js/main.js" %}"></script>
</body>
</html>

calapp/templates/calapp/index.html
<!doctype html>
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CALENDAR APP</title>
</head>

<body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">G.N.C.alendar Task Management Utility</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Calendar <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="./newtask">Add New Task</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <span class="navbar-text">
            Welcome, <b>{{ user.get_username }}</b>!
        </span>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><u>Log Out</u></a>
      </li>
    </ul>
  </div>
</nav>

<br><br>
<!--<table class="mx-auto table table-bordered" style="width: 95%">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Sunday</th>
      <th scope="col">Monday</th>
      <th scope="col">Tuesday</th>
      <th scope="col">Wednesday</th>
      <th scope="col">Thursday</th>
      <th scope="col">Friday</th>
      <th scope="col">Saturday</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td rowspan="2">Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Larry the Bird</td>
      <td>thingy</td>
    </tr>
  </tbody>
</table>-->

<h1>Events</h1>
{% if all_events %}
    <ul>
    {% for event in all_events %}
        <li>
        <b>{{ event.event_name }}</b> <a href="./deleteevent?id={{ event.id }}">X</a><br>
        <i>Starts: {{ event.start_time }}; Lasts {{ event.duration }}<br></i>
        Parent Task: {{ event.parent_task }}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>There are no events! Do something with your life!</p>
{% endif %}

<h1>Tasks</h1>
{% if tasks %}
    <ul>
    {% for task in tasks %}
        <li>
        <b>{{ task.task_name }}</b> <a href="./deletetask?id={{ task.id }}">X</a><br>
        <i>Deadline: {{ task.deadline }}; Priority: {{ task.get_priority_display }}</i><br>
        {% if task.estimatedDuration %}
            Estimated Duration: {{ task.estimatedDuration }} <a href="./allocatetasktime?id={{ task.id }}">Auto-Allocate Time</a><br>
        {% endif %}
        {% if task.subtask_set %}
            <ul>
            {% for subtask in task.subtask_set.all %}
                <li>{{ subtask.subtask_name }}</li>
            {% endfor %}
            </ul>
        {% endif %}
        <br>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>There are no tasks! Do something with your life!</p>
{% endif %}

<h1>Categories</h1>
{% if categories %}
    <ul>
    {% for category in categories %}
        <li>{{ category.category_name }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>There are no categories! Do something with your life!</p>
{% endif %}

</body>

</html>

calapp/templates/calapp/newtask.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">G.N.C.alendar Task Management Utility</a>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Calendar <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="./newtask">Add New Task</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <span class="navbar-text">
                  Welcome, <b>{{ user.get_username }}</b>!
              </span>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"><u>Log Out</u></a>
            </li>
          </ul>
        </div>
      </nav>

<div class="row">
    
    <h3 class="pl-4 col-3">Create New Task</h3>
</div>

<form action="/cal/newtask/" method="post" class="pl-5">
    <div class="font-weight-bold">
    {% csrf_token %}
    
    {% for field in form %}
    <div class="fieldWrapper row">
        <div class="col-2">
            {{ field.label_tag}}
        </div>
        <div class="col-1">
            {{ field }}
        </div>
    </div>
    {% endfor %}

    <!-- <div class="row">
        <div class="col-1">
            {{ form.task_name.label_tag }}
        </div>
        <div class="col-1">
            {{ form.task_name }}
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            {{ form.task_deadline.label_tag }}
        </div>
        <div class="col-2">
            {{ form.task_deadline }}
        </div>
    </div> -->
    


    <input type="submit" value="Submit" class="btn btn-light">
    </div>
</form>

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}CalcApp{% endblock %}</title>
  
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="container-fluid">
    <div class="row">
        <div class="col-3 display-4">
            Hi {{ user.username }}!
        </div>
        <div class="col-7"></div>
        <div class="col-2 display-4">
            <a href="{% url 'logout' %}">logout</a>
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            <a href="/cal">Continue to Schedule</a>
        </div>
    </div>
</div>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}